# @package _global_

defaults:
  - override /data: libero_omnigen2_pair
  - override /model: imagewam_ovis_u1
  - _self_

data:
  train:
    qwen_text_cache_dir: null
    require_text_cache: false

batch_size: 16
num_workers: 24
prefetch_factor: 2
persistent_workers: true

learning_rate: 1e-4
num_epochs: 10
max_steps: null
log_every: 10
save_every: 2500
eval_every: 100
eval_num_samples: 8
keep_latest_state_only: true

gradient_accumulation_steps: 1
weight_decay: 1.0e-2
mixed_precision: "bf16"
resume: null

model:
  proprio_dim: ${data.train.processor.proprio_output_dim}

wandb:
  enabled: true
  project: imagewam
  name: libero_ovis_u1_imagewam
