# @package _global_

defaults:
  - override /data: libero_omnigen2_pair
  - override /model: imagewam_omnigen2
  - _self_

batch_size: 12
num_workers: 24
prefetch_factor: 2
persistent_workers: true

learning_rate: 1e-4
num_epochs: 10
max_steps: null
log_every: 10
save_every: 1000
eval_every: 100
eval_num_samples: 8

gradient_accumulation_steps: 1
weight_decay: 1.0e-2
mixed_precision: "bf16"
resume: null

model:
  proprio_dim: ${data.train.processor.proprio_output_dim}


wandb:
  enabled: true
  project: imagewam
  name: libero_omnigen2_imagewam
